---
###################################################################
#
#  Ubuntu Trusty 64-bit management routines
#
#################################################################### vagrantbox role
- name: update Python-related requirements
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    autoremove: yes
    pkg:
      - zlib1g-dev
      - python2.7
      - python-pip
      - python-virtualenv
      - python-dev
      - git

- name: generate locales
  command: locale-gen

- name: configure locale and language settings
  command: "update-locale LANG=en_US.utf8 LANGUAGE=en_US:utf8"

